FROM ubuntu:22.04

RUN mkdir -p /root/

WORKDIR /root/
RUN apt update
RUN apt install git python3 python3-pip -y
RUN git clone https://github.com/justapig9020/PECO.git /root/peco

WORKDIR /root/peco
RUN git checkout docker
RUN pip install -r requirements.txt

WORKDIR /root/

CMD ["python3", "peco/judger/main.py", "-c", "project/judge.yaml"]