FROM ubuntu:22.04

RUN apt update
RUN apt install git python3 python3-pip -y
RUN git clone https://github.com/ntu-eclab-ca-ta/PECO /root/peco

RUN mkdir -p /root/project
WORKDIR /root/project
COPY judge.yaml /root/project/judge.yaml

WORKDIR /root/peco
RUN git checkout docker
RUN pip install -r requirements.txt

WORKDIR /root/

CMD ["python3", "peco/judger/main.py", "-c", "project/judge.yaml"]